# Blender Bridge — Shared Constants

PROTOCOL_VERSION = 1
DEFAULT_PORT = 9876
DEFAULT_HOST = "localhost"

# Wire protocol
HEADER_SIZE = 4  # bytes, big-endian uint32 length prefix
MAX_MESSAGE_SIZE = 50 * 1024 * 1024  # 50 MB

# Auto-feedback defaults
DEFAULT_INCLUDE_DIFF = True
DEFAULT_INCLUDE_SCREENSHOT = False
DEFAULT_SCREENSHOT_SIZE = 512
DEFAULT_SCREENSHOT_FORMAT = "PNG"

# Server
SOCKET_TIMEOUT = 1.0  # seconds, for accept() loop
RECV_BUFFER_SIZE = 65536
JOB_TTL_SECONDS = 600

# Poly Haven downloads. ``None`` selects the system temporary directory; set
# BLENDER_BRIDGE_PH_CACHE to share a durable cache between Blender sessions.
POLYHAVEN_CACHE_DIR = None

# Security policy
ALLOW_RAW_EXEC = False
AUDIT_LOG_FULL_CODE = False

# Engine aliases (Blender 4.x renamed EEVEE to BLENDER_EEVEE_NEXT)
ENGINE_ALIASES = {
    "EEVEE": "BLENDER_EEVEE_NEXT",
    "BLENDER_EEVEE": "BLENDER_EEVEE_NEXT",
    "WORKBENCH": "BLENDER_WORKBENCH",
}
VALID_ENGINES = {"CYCLES", "BLENDER_EEVEE_NEXT", "BLENDER_WORKBENCH"}

# Error codes
ERR_UNKNOWN_COMMAND = "UNKNOWN_COMMAND"
ERR_INVALID_PARAMS = "INVALID_PARAMS"
ERR_OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND"
ERR_EXECUTION_ERROR = "EXECUTION_ERROR"
ERR_CHECKPOINT_INVALID = "CHECKPOINT_INVALID"
ERR_SANDBOX_VIOLATION = "SANDBOX_VIOLATION"
ERR_PROTOCOL_MISMATCH = "PROTOCOL_MISMATCH"
ERR_INTERNAL_ERROR = "INTERNAL_ERROR"
ERR_UNSUPPORTED_IN_BACKGROUND = "UNSUPPORTED_IN_BACKGROUND"
ERR_JOB_NOT_FOUND = "JOB_NOT_FOUND"
